version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
#  # using with reverse proxy https://github.com/tim96/Reverse-proxy
#  # Environment values:
#  # VIRTUAL_HOST=www.example.com,example.com
#  # LETSENCRYPT_HOST=www.example.com,example.com
#  # LETSENCRYPT_EMAIL=info@example.com
#  default:
#    external:
#      name: nginx-proxy

services:
### PHP-FPM ##############################################
  php-fpm:
    restart: always
    container_name: "${CONTAINER_PHPFPM_NAME}"
    image: "${IMAGE_PHPFPM_NAME}"
    build:
      context: ./php-fpm
    volumes:
      - ${SYMFONY_APP_PATH}:/srv/app
      - ./logs/symfony:/srv/app/var/log
    networks:
      - backend

### NGINX ##############################################
  nginx:
    restart: always
    container_name: "${CONTAINER_NGINX_NAME}"
    image: "${IMAGE_NGINX_NAME}"
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    depends_on:
      - php-fpm
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    #expose:
    #  - 80
    #  - 443
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${SYMFONY_APP_PATH}/public:/srv/app/public:ro
    ports:
      - ${NGINX_PORT}:80
    networks:
      - backend
      - default

### MySQL ################################################
  db:
    restart: always
    container_name: "${CONTAINER_MYSQL_NAME}"
    image: "${IMAGE_MYSQL_NAME}"
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    networks:
      - backend
