version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
#  # using with reverse proxy https://github.com/tim96/Reverse-proxy
#  # Environment values:
#  # VIRTUAL_HOST=www.example.com,example.com
#  # LETSENCRYPT_HOST=www.example.com,example.com
#  # LETSENCRYPT_EMAIL=info@example.com
  default:
    external:
      name: nginx-proxy

services:
### PHP-FPM ##############################################
  php-fpm-1:
    restart: always
    build:
      context: ./php-fpm
    volumes:
      - ${SYMFONY_APP_PATH}:/srv/app
      - ./logs/symfony:/srv/var/log
    networks:
      - backend

### NGINX ##############################################
  nginx-1:
    restart: always
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    depends_on:
      - php-fpm-1
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    #expose:
    #  - 80
    #  - 443
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      # For symfony 4 / 5
      - ${SYMFONY_APP_PATH}/public:/srv/app/public:ro
      # For symfony 3
      # - ${SYMFONY_APP_PATH}/web:/srv/app/web:ro
    ports:
      - ${NGINX_PORT}:80
    networks:
      - backend
      - default
